### ISSUE TITLE
Class naming conventions

### ISSUE THREAD

**Issue by livmackintosh** [PHPAuth/PHPAuth#135]
Not sure if this can/should be changed immediately but Composer includes files based on their class name. E.g:

```php
<?php
require __DIR__ . '/vendor/autoload.php';
$auth = new \PHPAuth\Auth($dbh...);
?>
```
Would look for the file Auth.php whereas naming convention is auth.class.php.

I tried instantiating \PHPAuth\auth.class but it throws a syntax error (because of the period?)

**Comment by KarelWintersky** [comment]
https://jtreminio.com/2012/10/composer-namespaces-in-5-minutes/ may be this can help?

**Comment by cuonic** [comment]
Ok so we need to rename `auth.class.php` to `Auth.php` and `config.class.php` to `Config.php` ?

**Comment by bugada** [comment]
Taken from StackOverflow

1.    PSR-0 converts the class name into a path name (underscores and backslashes from namespaces are converted into a directory separator), adds ".php" at the end, and tries to find this file in the path that you have given in the composer.json file. A class myNamespace\myClass and "psr-0":{"myNamespace\\": "src"} will try to load src/myNamespace/myClass.php.
2.    PSR-4 only works with namespaces. It removed the namespace prefix given in composer.json from the full class name, and the remainder is converted into a path, ".php" added at the end, and searched in the path given. A class myNamespace\myClass and "psr-4":{"myNamespace\\": "src"} will try to load src/myClass.php.
3.    Classmap autoloading will work by scanning all the files for classes, interfaces and traits (everything that can be autoloaded), and compiles an array map of it. It works with any file name schema and any directory layout, but try to avoid it because it will need an update to the map every time you add a new class. Also, it takes time to scan the files while installing, and it takes some CPU and memory to load and hold that map.

**Comment by livmackintosh** [comment]
Okay. Well the autoloading functionality built into composer is based around the PSR-4 specification - which can be found here: [PSR-4 - Autoloader](http://www.php-fig.org/psr/psr-4/). If PHPAuth is committed to Composer support it should conform to the PSR-0 (depreciated) or the newer PSR-4 specification. The specification states "The terminating class name corresponds to a file name ending in .php. The file name MUST match the case of the terminating class name." which implies that the classes "Auth" and "Config" should have file names "Auth.php" and "Config.php" respectively.

I hope this helps. :smile_cat: 

Liv

**Comment by cuonic** [comment]
Ok well if I did things correctly that should of moved class naming over to the PSR-4 specification. Can anyone check things work out of the box with Composer ?

**Comment by PaulKish** [comment]
@cuonic tested this change, works well,I was able to test this using composer. My suggestions on this would be 
-remove the extra classes auth.class.php and config.class.php ( I am not sure if this will  cause a bc break)
-fix how the language file is called since one has to manually include it ( my suggestion would be a property that specifies the file to load)

**Comment by cuonic** [comment]
Great, glad that it works great for you. What do you mean by "remove the extra classes  auth.class.php and config.class.php", now there is `Auth.php` and `Config.php` ? 

There is a language file discussion going on at Issue #136

**Comment by cuonic** [comment]
Also just added PHPAuth to Packagist: https://packagist.org/packages/phpauth/phpauth
Installation now works with `composer require phpauth/phpauth`

![composer-magic](https://cloud.githubusercontent.com/assets/821228/10993710/209a366e-8471-11e5-9c7e-64c0a2e790f9.png)

**Comment by PaulKish** [comment]
@cuonic the extra files seem to be there when I pulled used the previous composer setup. Thanks for setting it up on Packagist :thumbsup:

**Comment by cuonic** [comment]
Should be fixed with the latest release
