### ISSUE TITLE
[Suggestion] Store language strings as JSON and provide constructor to create $lang object?

### ISSUE THREAD

**Issue by livmackintosh** [PHPAuth/PHPAuth#136]
I'm not really sure what best practices are surrounding things like strings but I feel like these should be stored in JSON instead of as a PHP array? I feel like a constructor class would be more appropriate where the ISO language code (e.g "en-GB") can be passed as a parameter. I feel like it would be more natural in code logic?

I'm not sure if this would provide any significant usability improvement but it would provide consistency in code structure (everything is provided by the PHPAuth namespace)?

I'd love to know what people think?

Liv

**Comment by cuonic** [comment]
I'm not sure that having language files stored in JSON instead of directly as an array will change much, all the class will do is load the JSON file and interpret into... an array, so in the end it's all the same. Every PHP project uses their own language storage method, I've seen INI, YAML, JSON, Arrays... but i think we can safely stick with just a simple PHP array at the moment.

The other idea you have is interesting though: loading the class with just the ISO language code and letting it load the required file, or fall back to `en_GB`, I think it would be better than loading the language file before loading the class and then passing the array to the class.

**Comment by PaulKish** [comment]
I agree with this suggestion 
>The other idea you have is interesting though: loading the class with just the ISO language code and letting it load the required file, or fall back to en_GB, I think it would be better than loading the language file before loading the class and then passing the array to the class.

This is cleaner IMO

**Comment by cuonic** [comment]
I'm pushing this in the next few minutes
