### ISSUE TITLE
$_COOKIE[$this->config->cookie_name] never set

### ISSUE THREAD

**Issue by iNewLegend** [PHPAuth/PHPAuth#168]
how properly save the login ? the class only use $_COOKIE[$this->config->cookie_name]
why not save cookie in login ? why its not in front of this the page some people can't do not understand... that it should be added manually ? is is there a way it can be included ? (ofc) but the what is the best way ?

**Comment by glowdemon1** [comment]
Yes, you have to set the cookie yourself.

Why?
Because the writer of this script doesn't how he can set the cookie because this script (that is supposed to set the cookie) might be executed while the header is sent, and then it's impossible to set a cookie unless you have started and output buffer.
