### ISSUE TITLE
lastInsertId(); does not work with PostgreSQL

### ISSUE THREAD

**Issue by jameslitwin** [PHPAuth/PHPAuth#178]
In Auth class the PDO function lastInsertId() does not work with PostgreSQL database. You need to name of the sequence that you wish to retrieve the last inserted ID.

example:
lastInsertId('users_id_seq')

http://codingexplained.com/coding/php/postgresql-last-insert-id-not-working-pdo

**Comment by shobekhan** [comment]
Hi,

I have problem with postgresql

On the following line

$query = $this->dbh->prepare("INSERT INTO {$this->config->table_users} VALUES ()");

In order to fix it 

I added the following line of code

// find driver
$driver = $this->dbh->getAttribute(\PDO::ATTR_DRIVER_NAME);

// pgsql fix
if('pgsql' == $driver) {
	$query = $this->dbh->prepare("INSERT INTO {$this->config->table_users} (email, password) VALUES (?, ?)");
	$query->bindParam(1, $email, \PDO::PARAM_STR);
	$query->bindParam(2, $password, \PDO::PARAM_STR);
} else {
	$query = $this->dbh->prepare("INSERT INTO {$this->config->table_users} VALUES ()");
}

**Comment by cuonic** [comment]
This is a start but would probably break MySQL compatibility: http://stackoverflow.com/a/35441147
