### ISSUE TITLE
Change Password With Out sending email

### ISSUE THREAD

**Issue by de3v0** [PHPAuth/PHPAuth#182]
Hello, i'm trying to update a password of another User (Backoffice purposes)
Do i need to make a request, receive the email and then use the resetPass method? 
Or there is any other way to do it ?

Thankyou

**Comment by oxxido** [comment]
Hey, You should already solve this, but just in case, you need to use the hash function on new pass and save it to db, here i'm using eloquent:
`$user->password = $auth->getHash($_POST['newPassword']);`
`$user->save();`

**Comment by de3v0** [comment]
i'll test it ASAP. Thanks for the reply

**Comment by de3v0** [comment]
Sorry, that wasn't what i was looking for. Lets say that theres an logged user(Administrator), that has a list of users. The objective is to update password of this other users.

**Comment by cuonic** [comment]
There isn't currently a function to do this, the only one available, `changePassword` requires the user's current password. Seperating this function into two would be necessary

**Comment by oxxido** [comment]
> The objective is to update password of this other users.
there's no function for this, unless you know the password of the other user, that's why you need to write your own function. this is easy to do, if you have programming skills then you just need to update the password field in the table, $mockSql = "... SET 'password'='".$auth->getHash($_POST['newPassword'])."' WHERE user_id=$something LIMIT 1". Which is the same i did on my jun 15 comment, but using eloquent
