### ISSUE TITLE
ZxcvbnPhp - register

### ISSUE THREAD

**Issue by Quentinb** [PHPAuth/PHPAuth#204]
First, great work guys, thanks for the efforts!

I am following your basic example to secure a page and have extended it a tad to test the features by adding a $auth->register followed by $auth->login. the registration fails at $zxcvbn = new Zxcvbn();

I've pulled the Zxcvbn repo and placed it into the root folder of my test site. This does not resolve the issue as Zxcvbn is not found.

To get going, I simply pulled this repo and FTP'd it up to a test server. Created the DB and run the MySql script. DB connection is fine.

**Comment by Conver** [comment]
That's because PHPAuth is meant to be installed with composer now, composer would have installed Zxcvbn, PHPMail and such.

You need to include the Zxcvbn class before `$zxcvbn = new Zxcvbn();` 

Other installation method are planned in next release.

**Comment by ebo285** [comment]
Hello,

i installed with composer, and ran into the same problem.
Why PHPAuth doesn't include himself files needed to use Zxcvbn ?

could you tell what includes we need exactly ?

Eric.

**Comment by cuonic** [comment]
PHPAuth does not include external libraries for the following reason:

Imagine if a major vulnerability or fatal error was found in the version of PHPMailer or Zxcvbn that shipped with PHPAuth, your application would not work, and it would become *our* problem to update PHPAuth with fixed versions of the dependencies so that your application can work again.

This is partially why dependency management was invented. Installing and keeping dependencies up to date is now *your* problem so that *we* can focus on improving and fixing the actual base library, PHPAuth.

To install with Composer all you need to do is:
  - Execute: `composer require phpauth/phpauth`
  - Add the followig line to your application `require_once("vendor/autoload.php");`
  - '$phpauth = new \PHPAuth\PHPAuth($dbh);`
