### ISSUE TITLE
Update composer package

### ISSUE THREAD

**Issue by KarelWintersky** [PHPAuth/PHPAuth#295]
@Conver , please, update composer package to latest version.

https://packagist.org/packages/phpauth/phpauth

**Comment by Conver** [comment]
That's a job for @liamjack, I do not have access to that site.

**Comment by KarelWintersky** [comment]
@liamjack , please, update composer package

**Comment by PatteJun** [comment]
Any ideas, when the composer package will be updated?

**Comment by KarelWintersky** [comment]
@PatteJun  use `"phpauth/phpauth": "dev-master"`

**Comment by liamjack** [comment]
@KarelWintersky I don't seem to have any ownership rights for the package on packagist.org, so I haven't been able to done anything for there.

I have created [a new release (v1.1.2)](https://github.com/PHPAuth/PHPAuth/releases/tag/1.1.2) because I configured Packagist to auto-update, and it appears to have worked, packagist lists v1.1.2: https://packagist.org/packages/phpauth/phpauth#1.1.2

**Comment by KarelWintersky** [comment]
@liamjack , so who is owner of our project at packagist? :)

```
→ composer require phpauth/phpauth
Using version ^1.1 for phpauth/phpauth
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing google/recaptcha (1.1.3): Loading from cache
  - Installing phpmailer/phpmailer (v6.0.5): Loading from cache
  - Installing bjeavons/zxcvbn-php (0.3.0): Loading from cache
  - Installing phpauth/phpauth (1.1.2): Downloading (100%)
```

nice.

**Comment by liamjack** [comment]
Good question... I remember doing the initial configuration, but then it moved into the `PHPAuth` organisation, which I don't seem to be an owner of anymore. Maybe @Conver can take a look, if you login to packagist.org via Github and checkout "My packages" ?
