### ISSUE TITLE
Small issue with attempts table and using IP

### ISSUE THREAD

**Issue by eric-hoppenworth** [PHPAuth/PHPAuth#396]
I am using PHPAuth to lockdown an administrative web app that is used by our staff.  Many users sit in one office, all on one IP.
The attempts table reads (and counts) based on IP, so if different users mess up their own passwords, we can hit the attempts limit fairly quickly, essentially locking out all of the staff.
I can get around this myself by overriding some of the Auth class's functions, I am considering adding a username field to the attempts table, and then counting the attempts by including BOTH username and IP in the WHERE clause.
Is this a terrible idea? Is there something already built in that will help me out that I am not seeing?

**Comment by louis123562** [comment]
Instead of the username, you could ask for the user-agent.

**Comment by jmhumphrey** [comment]
I added a browser fingerprint var to a new derived "login" class function: loginWithBrowserFingerprint($email, $password, $bfp, $remember = 0, $captcha_response = null).  Im using https://github.com/Valve/fingerprintjs2 on the front end to generate my fingerprint.  Of course this isn't full proof and it gets a little hacky but gives more entrophy for identifing your client.  This is the same principle as what louis was mentioning just a bit more complex and involves some code on the client side.

**Comment by louis123562** [comment]
Interesting. Never thought about creating a fingerprint via the different installed fonts on the client :) Are you aware of `allow_concurrent_sessions`? How do you handle it?

**Comment by jmhumphrey** [comment]
Hey louis, Im just spit-balling and haven't done any test but I would think an additional field in the session table would be needed to identify the device itself  or perhaps the hash function could be changed to incorporate the browser finger print as part of the hash calculation.    This could create an extra layer of security but could also annoy the user possibly with false negatives ;).

From everything i've read Browser fingerprinting isn't ideal for authentication because its not always 100% correct.  Its more like 80% correct and even at that if you have several of the exact same configuration computers on the same lan it would be less accurate.

So I think for the use case of measuring login attempts it works but may not be a good idea when it comes to actually tracking sessions.  I think the cookie is the way to go.  Im no expert though so take all that with a grain of salt haha.

**Comment by louis123562** [comment]
Oh okay :)

In my opionion there is no a way to really identify a client without two-factor-auth, because everything can be faked (in worst case). But storing and comparing (Hello Big Data!) as much as possible could at least be the thing for usual clients. But be aware of the GDPR, you will need to have the agreement of the user and inform him etc. etc. - Not really helpful for us germans.

I guess Two Factor Auth is going to be the next big thing here on PHPAuth...^^

**Comment by jmhumphrey** [comment]
I think 2FA would be a welcome addition.  You are correct about GDPR and I think and hope the laws will become even more stringent in Europe and hopefully someday the US where I hail from.  

This is what I use on my site.
`<?php
	$fcCookeiDisclosureExists = \Delight\Cookie\Cookie::exists('fc-cookie-disclosure');

	if(!$fcCookeiDisclosureExists){
?>
	<div id="cookie-disclosure" class="fixed-bottom m-4 mb-0 alert alert-info alert-dismissible fade show" role="alert">
    		<strong>This site uses cookies!</strong>
    		<p> 
    		By using this site you agree to the use and storage of cookies on your local machine.  
    		We will not collect any information and distribute to a third-party for marketing.  You can see our
            policy by visiting <a href="cookiePolicy.php">Cookie Policy</a>.
    		</p>
    		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    			<span aria-hidden="true">&times;</span>
    		</button>
    	</div>
<?php 
	}
?>`

Regards

**Comment by Conver** [comment]
See #413
