### ISSUE TITLE
No salt field, so how do you verify the passwords for login()?

### ISSUE THREAD

**Issue by logicandluck** [PHPAuth/PHPAuth#48]
getHash() in auth clearly uses a randomly generated salt in order to hash the password. I don't see anything happening to the plain text password being passed to login(). How am I supposed to hash the login attempt and compare it to the DB if there is no salt field in the DB anymore?

I added this functionality back in (returning and storing the salt from getHash) but I see I might have to further change the login() function back in order to accurately deduce a successful login.

Please correct me if I am wrong.

**Comment by mooztik** [comment]
PHPAuth is now using 'password.php' to handle encryption(bcrypt). in 'password_verify()' function, the password is crypted with hashed password and this function compare the length of the result.
i currently does not understand how it really work, but it work :D (some new things to learn about encryption)
then i deduce the salt does'nt need to be stored anymore.

**Comment by cuonic** [comment]
Hi guys,

Using a `salt` field turned out to be a case of data replication, the salt is already stored in the password. A bcrypt hash contains the hash cost, the salt and the cipher text (take a look [here](http://stackoverflow.com/a/6833165) for a better explanation)

A salt is generated randomly for each user by the bcrypt hashing function.

Removing the salt field from the database and from the codebase should not have required any changes, and should function correctly with your previous database.

@mooztik : `password.php` is a compatibility layer that allows PHP versions 5.3.7 to 5.5 to use the [password_* functions](http://php.net/password) that were introduced in PHP 5.5 that are essentially wrappers for using `crypt()`.

Hope this clears up any confusion, if you have any other questions, don't hesitate to ask :)

**Comment by mooztik** [comment]
thank's, it's more clear.
